# Generated by Django 4.0.6 on 2022-07-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='watchlist',
            new_name='people_watching',
        ),
    ]
