# Generated by Django 4.0.6 on 2022-07-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_closed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='closed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
